### ISSUE TITLE
Bug when address is changed MB85RC.begin(Wire , DEV_ADDR)

### ISSUE THREAD

**Issue by SSPW** [RAKWireless/RAK1500x-MB85RC#1]
I tried using Adafruit 256Kbit / 32KByte module with this library, while waiting for some RAK15004 modules to arrive.

The library example works fine with the RAK15004 module and 0x56.

Using the library example and changing ...

#define DEV_ADDR    MB85RC_DEV_ADDRESS
...
Wire.begin();
  while(MB85RC.begin(Wire , DEV_ADDR) == false) 
  
to

#define DEV_ADDR    0x50 

with a stock Adafruit module, the 0x50 address passed is not used and the module is not found.
Forcing the adafruit module to 0x56 with 10k resistors to Vcc on A2 and A1, the library example works.

I understand all the RAK Fram modules come with 0x56. 
However a RAK user might want/need to modify a rak module A0/A1/A2 config for some reason, ie conflict with other modules. etc.
And it that isnt supported, 0x56 is the only address to be supported, then why pass an address?

**Comment by SSPW** [comment]
Problem found in
void RAK_MB85RC::getID(uint16_t *manuID, uint16_t *prodID)

line
_i2cPort->write(0xAC);

where 0xAC is 2 * 0x56

needs to be changed to:
_i2cPort->write(_deviceAddress * 2);

to support other device addresses

**Comment by beegee-tokyo** [comment]
Thanks for reporting the issue. We will test it and if it works it will changed in the next release.
